### ISSUE TITLE
Wording of Requirements

### ISSUE THREAD

**Issue by jbrucker** [koakatta/ku-polls#8]
Requirements state what the app should actually do, not what it "can" do.

Please reword your requirements.   And please don't use the abbreviation "app".  Write "application" or "system".

Customer - wrong word.  They are not buying anything.  Use "Visitor". Words and roles matter. 

Here is one example but you need to rewrite MANY requirements:

> 1. The app can display all active polls.

Better:

> 1. The default landing page displays a list of all active polls.

**Comment by koakatta** [comment]
fixed requirement in requirement wiki
